version: "3.7"

services:
  web:
    build:
      context: ./humanitarian_feedback
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    command: gunicorn humanitarian_feedback.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/root/humanitarian_feedback/staticfiles
    expose:
      - 8000
    env_file: .env
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    command: sh -c "chmod 755 /root && nginx -g\"daemon off;\""
    volumes:
      - static_volume:/root/humanitarian_feedback/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  static_volume:
